name: "gsm"
version: "0.1.0"
usage: "Secrets loading via Google Secret Manager"
description: "This plugin provides automatic loading of secrets from Google Secret Manager"
command: "$HELM_PLUGIN_DIR/bin/helm-gsm"
#platformCommand:
#  - os: linux
#    arch: i386
#    command: "$HELM_BIN list --short --max 1 --date -r"
#  - os: linux
#    arch: amd64
#    command: "$HELM_BIN list --short --max 1 --date -r"
#  - os: windows
#    arch: amd64
#    command: "$HELM_BIN list --short --max 1 --date -r"
